### ISSUE TITLE
Should use latest version of Angular CLI

### ISSUE THREAD

**Issue by KyleMcNutt** [teracyhq/docker-files#27]

**Comment by hoatle** [comment]
@KyleMcNutt please checkout the latest tag here, it should have the latest @angular/cli version installed https://hub.docker.com/r/teracy/angular-cli/tags/

You can use differrent versions, too.

Let me know if there is anything wrong.

Later when creating issues, please provide more details, thank you.

**Comment by KyleMcNutt** [comment]
Sure enough! Thanks!
