### ISSUE TITLE
angular-cli docker-files

### ISSUE THREAD

**Issue by maraymer** [teracyhq/docker-files#28]
I noticed while working with the angular-cli example it says:

> root@265dcf6e7241:/opt/new-ng2-app# ng set --global packageManager=yarn
> and then:
> 
> $ cd new-ng-app
> 

There is no new-ng-app at that point?  It seems like something is missing?

**Comment by hoatle** [comment]
thank you @maraymer, it's fixed now.

**Comment by maraymer** [comment]
@hoatle my pleasure to help.  There is still a jump in the flow of the directions?  in the first block the user is in new-ng2-app but the first thing that the next block instructs the user to do is cd into new-ng2-app?  Am I missing something?

**Comment by hoatle** [comment]
@maraymer the 1st "cd" is within a docker container, the 2nd "cd" is from the host.

maybe this could be clearer:

"exit" the running container and then:

```
$ cd new-ng2-app
```

**Comment by maraymer** [comment]
thanks.  Yes, it would be more clear for people new to docker.  I'm
reviewing your development environment to use inhouse with my company --
I'm new to docker :-)

**Comment by hoatle** [comment]
@maraymer I've updated the README docs to make it clearer.

Don't hesitate to ask us any questions and support about Docker and its workflow, we're here to help :-)

**Comment by maraymer** [comment]
@hoatle awesome. I'll be sure to get back with you.  I'm working in all three major environments with complications in Windows.  One of my units I use when traveling is a little low memory Windows 8 unit (2GB of RAM) which I'd like to be able to use a little more frequently.  That's requiring me to use Docker Toolbox.
