### ISSUE TITLE
Trying to run command it is displayed /bin/bash No such file or directory

### ISSUE THREAD

**Issue by iamgoangle** [teracyhq/docker-files#37]
I tried to run this command on my terminal
`docker run -it -v "$PWD":/usr/src -w /usr/src -p "3000:3000" teracy/create-react-app /bin/bash root@4b15ab7dbf21:/usr/src# create-react-app . root@4b15ab7dbf21:/usr/src# HOST=0.0.0.0 && npm start`

I would like to confirm that should I change some parameter to make it run on my machine?

This is an error message that I got it

`bin/bash: root@4b15ab7dbf21:/usr/src#: No such file or directory`

**Comment by hoatle** [comment]
Hello @iamgoangle, I'm not sure about your case, I've checked, it works as expected.

How can I reproduce your mentioned problem?

**Comment by hoatle** [comment]
I followed https://github.com/teracyhq/docker-files/tree/master/create-react-app#how-to-use

**Comment by hoatle** [comment]
closed as no reply from @iamgoangle. Feel free to re-open if you're still having the problem.
