### ISSUE TITLE
Tag for Angular CLI 1.7

### ISSUE THREAD

**Issue by karllhughes** [teracyhq/docker-files#51]
My team has been adding this line to our Dockerfiles to update Angular CLI to 1.7:

```
FROM teracy/angular-cli:1.5.0
RUN npm update -g @angular/cli@1.7.4
```

Is it possible to release a tag for Angular CLI 1.7 so we don't have to do this? I looked into it, but it seems to be an environmental setting for the Travis build. If there's any way I can help, just let me know, happy to submit a PR.

**Comment by karllhughes** [comment]
Actually, does this work? https://github.com/teracyhq/docker-files/pull/52

**Comment by hoatle** [comment]
https://hub.docker.com/r/teracy/angular-cli/tags/ the tag is available now, thank you.
