### ISSUE TITLE
jessie-updates moved to archive.debian.org

### ISSUE THREAD

**Issue by 6utt3rfly** [teracyhq/docker-files#59]
On March 20, 2019, the Debian project moved the repository jessie-updates to archive.debian.org.

This doesn't have to be part of the base image, but would make it easier:
`COPY sources.list /etc/apt/sources.list`

[sources.list]:
deb http://deb.debian.org/debian/ jessie main
deb-src http://deb.debian.org/debian/ jessie main

deb http://security.debian.org/ jessie/updates main
deb-src http://security.debian.org/ jessie/updates main

deb http://archive.debian.org/debian jessie-backports main
deb-src http://archive.debian.org/debian jessie-backports main

And to update apt-get:
`apt-get -o Acquire::Check-Valid-Until=false update`

**Comment by hoatle** [comment]
hello @6utt3rfly, I'm not sure if we need to do anything with the project as from my observation, everything just works great. If you think we need to update any, feel free to send a PR then, thank you.

**Comment by 6utt3rfly** [comment]
Hello @hoatle , it looks like if I use the `latest` image, then I don't have any problems with `apt-get update`, but if I use the last tagged release, (in my case, `teracy/angular-cli:1.7.4`) then `apt-get-update` gives an error. Maybe the image just needs to be re-tagged from latest to incorporate downstream changes?

**Comment by 6utt3rfly** [comment]
`# apt-get update
Ign http://dl.google.com stable InRelease
Get:1 http://dl.google.com stable Release.gpg [819 B]
Get:2 http://dl.google.com stable Release [943 B]
Get:3 http://security.debian.org jessie/updates InRelease [44.9 kB]
Get:4 http://dl.google.com stable/main amd64 Packages [1110 B]
Ign http://deb.debian.org jessie InRelease
Ign http://deb.debian.org jessie-updates InRelease
Get:5 http://security.debian.org jessie/updates/main amd64 Packages [825 kB]
Get:6 http://deb.debian.org jessie Release.gpg [2420 B]
Ign http://deb.debian.org jessie-updates Release.gpg
Get:7 http://deb.debian.org jessie Release [148 kB]
Ign http://deb.debian.org jessie-updates Release
Get:8 http://deb.debian.org jessie/main amd64 Packages [9098 kB]
Err http://deb.debian.org jessie-updates/main amd64 Packages

Err http://deb.debian.org jessie-updates/main amd64 Packages

Err http://deb.debian.org jessie-updates/main amd64 Packages

Err http://deb.debian.org jessie-updates/main amd64 Packages

Err http://deb.debian.org jessie-updates/main amd64 Packages
  404  Not Found
Fetched 10.1 MB in 6s (1503 kB/s)
W: Failed to fetch http://deb.debian.org/debian/dists/jessie-updates/main/binary-amd64/Packages  404  Not Found

E: Some index files failed to download. They have been ignored, or old ones used instead.
`

**Comment by hoatle** [comment]
teracy/angular-cli:1.7.4 is very old to be maintained and I've added 2 latest versions: teracy/angular-cli:6.2 and teracy/angular-cli:7.3 which do not have any problem with the debian repository.

so we can close the issue then.
